### PR TITLE
fix #208 : bug in loadout export where WeaponUnderbarrel should be WeaponUnderbarrelMagazine

### LINKED ISSUE #208: primaryWeaponUnderbarrelMagazine not copied to clipboard
1. Place a CSAT-pacific grenadier.
2. Copy its loadout to the clipboard using the grad-loadout logging feature in Eden. 
image
3. Check the clipboard content in a texteditor

You will notice 2x entries with the name `primaryWeaponUnderbarrel` right after one another. 
The second entry needs to be renamed to `primaryWeaponUnderbarrelMagazine` in order to function properly.

### PR DESCRIPTION
**Pull request by Fusselwurm**

### CODE REVIEW

**Comment by b-mayr-1984** [comment]
@Fusselwurm where can I download the CI artifact in order to test it?

**Review by b-mayr-1984 — COMMENTED** [review]
@Fusselwurm where can I download the CI artifact in order to test it?

**Review by AdlerSalbei — APPROVED** [review]

**Review by b-mayr-1984 — CHANGES_REQUESTED** [review]
I'd say that [line 44](https://github.com/gruppe-adler/gruppe_adler_mod/blob/531c1c9f3b72e328d8e3435933ec53848d0c23a8/addons/getLoadoutsFromUnits/functions/fnc_getWeapon.sqf#L44) should also be changed, even though it is currently just a comment. 
Otherwise the code just doesn't look consistent.

Alternatively the entire comment block around line 44 could just be removed. 
(But I don't know if someone might still need this in the future.)

**Comment by Fusselwurm** [comment]
> @Fusselwurm where can I download the CI artifact in order to test it?

afaics https://github.com/gruppe-adler/gruppe_adler_mod/actions/runs/4332763655 at the bottom

**Comment by b-mayr-1984** [comment]
> > @Fusselwurm where can I download the CI artifact in order to test it?
> 
> afaics https://github.com/gruppe-adler/gruppe_adler_mod/actions/runs/4332763655 at the bottom

@Fusselwurm just tested it and it works. 🙂 

I still think though that this change regarding line 44 still should be incorporated.
> I'd say that [line 44](https://github.com/gruppe-adler/gruppe_adler_mod/blob/531c1c9f3b72e328d8e3435933ec53848d0c23a8/addons/getLoadoutsFromUnits/functions/fnc_getWeapon.sqf#L44) should also be changed, even though it is currently just a comment. Otherwise the code just doesn't look consistent.
> 
> Alternatively the entire comment block around line 44 could just be removed. (But I don't know if someone might still need this in the future.)

**Review by b-mayr-1984 — APPROVED** [review]

**Pull request merged**
