### PR TITLE
make rubber boats as maneuverable as they should be

### PR DESCRIPTION
**Pull request by Fusselwurm**
still doesnt fix the general mechanics, but at least we wont get stuck anymore

rudderForceCoef = 1 :  ~~https://www.youtube.com/watch?v=dIp4wbSeyqs~~

rudderForceCoef = 0.3 :  https://youtu.be/HItwXve4k8I

### CODE REVIEW

**Comment by nomisum** [comment]
how does this work out when driving fast and turning? does it make the boat completely unstable?

**Comment by Fusselwurm** [comment]
still stable, but feels a bit magic to be able to turn on a dime at full speed

**Comment by McDiod** [comment]
Looks a little over the top to me. Maybe set this to halfway between the video and vanilla?

***

> feels a bit magic to be able to turn on a dime at full speed

Apparently there is also `rudderForceCoefAtMaxSpeed`. Not sure if it might be of use here.

**Comment by Fusselwurm** [comment]
@McDiod I kept rudderForceCoefAtMaxSpeed at the default which is like 0.001 or so because its already so much lower than the main value, but… yes will try to lower it even more.

**Comment by Fusselwurm** [comment]
edit: reduced rudderForceCoef a lot, I hope this strikes a good balance between sluggish and crazy.

ftr: `rudderForceCoefAtMaxSpeed` is broken. it does nothing except when you're at absolute max speed (so: never)

**Comment by Fusselwurm** [comment]
also here is a potato cam video of someone proving that even with `rudderForceCoef = 1` I was not overdoing it really  

https://www.youtube.com/watch?v=DvztTqrqQm4

**Review by McDiod — APPROVED** [review]

**Pull request merged**
