### PR TITLE
fix #21: move cinematicSpec from optionals to addons

### LINKED ISSUE #21: move cinematicSpec to addons
- [x] test cinematicSpec in a "real" scenario ( 2+ people)
- [x] remove default keybinding (because it might conflict with other things)
- [x] fix #31
- [x] #41 ensure that leaving ACE spec also makes you leave the BIS cam :grimacing: 
- [ ] #60 move to addons

### PR DESCRIPTION
**Pull request by Fusselwurm**
move cinematicSpec component from /optionals into /addons, making it mandatory.

**Note:**
* The hotkey is per default unmapped – no one will accidentally use this feature
* There is a bug where if you're in this mode, a scenario that's unaware of the component will not be able to pull you from spectator. there is a workaround, and the user *will* be warned, see #41 
* Users currently will leave the TFAR spectator channel while in being in cinematicSpec . It's quite the unintentional feature.

### CODE REVIEW

**Comment by Fusselwurm** [comment]
*welp, moving files means there's no line comments. still, reviewing is easy - just look at EVERYTHING in `/addons/cinematicSpec`*

**Comment by chris579** [comment]
`/addons/cinematicSpec/functions/fn_watchEGSpectator.sqf`
Is injecting into spectator display possible? XEH maybe, better than pfh all the time.

**Comment by Fusselwurm** [comment]
@chris579 I could probably  [attach a handler](https://community.bistudio.com/wiki/User_Interface_Event_Handlers) to the "Unload" event on the spectator display. Probably. Much more interesting would be to add a handler to an event that fires when a display is being created, but I cant see one. :/

**Comment by chris579** [comment]
`onLoad`/`onUnload`, just add it via config. Make sure that the default ones are preserved.

**Comment by chris579** [comment]
As you are just registering a keyDown event you could do it like this:
```cpp
class RscDisplayEGSpectator {
    onKeyDown = QUOTE(_this call FUNC(ui_eg_handleKeyDown));
};	
```

Move the info message to the func.

**Comment by chris579** [comment]
You don't even need this whole loop + the keyDown evh. This is handled by cba completely.

https://github.com/gruppe-adler/gruppe_adler_mod/blob/605e54b5358b2d7edcf9c012e13817b6ddf1011a/addons/cinematicSpec/XEH_preInit.sqf#L6-L12
Change the keybind to call a func, check in there which spectator is being used and then go on with the contents of `ui_ace_handleKeyDown` and `ui_eg_handleKeyDown`. You could even merge both scripts to one keydown script that is called by cba keybind.
Removes the need of the watchdog and makes everything more straight forward.

**Comment by McDiod** [comment]
Wasn't there some kind of problem with using the keybind directly @Fusselwurm ? Something about EG Spec overriding keypresses.

Otherwise yea, watchEGSpectator could be removed and with it any concerns that users might have about a possible negative impact of this formerly optional component. As long as the key is not bound, nothing would ever happen.

**Comment by nomisum** [comment]
Tried and failed adding CBA_fnc_addKeybind as suggested. EGSpectator/ACE Spectator overwrite without mercy. As soon as the spectator is running, nothing is called anymore.

**Pull request merged**
