### PR TITLE
Direct connect

### PR DESCRIPTION
**Pull request by DerZade**
* Refactoring of some of the code 
* Additional feature to select port when right clicking button in main menu.

### CODE REVIEW

**Comment by McDiod** [comment]
fn_onButtonPortOK should call fn_onButtonConnect and pass the port. fn_onButtonConnect will check if there is a saved password and if it worked the last time and then either call the password dialog or connect to server. The way this is set up right now completely bypasses the password check.

**Comment by McDiod** [comment]
wat

**Comment by McDiod** [comment]
@DerZade irgendwelche Einwände gegen die Änderungen?

**Comment by DerZade** [comment]
@McDiod Nope. Sieht gut aus 👌

**Pull request merged**
