### PR TITLE
Added new bags and insignias

### PR DESCRIPTION
**Pull request by Synch2k**
Added 4 new medical variants of the messenger bag (Olive, Black, Coyote, _Civil_)
Added 2 new drafts for medical insignias (Red Cross and Red Crystal) - those are subject to change, but are still usable for the next mission anyway

mod was build and tested successfully

### CODE REVIEW

**Comment by Fusselwurm** [comment]
Is there a way scenario creators will easily know which item depends on LoW DLC content? :thinking:

**Comment by Synch2k** [comment]
Good Point :thinking: what would be the impact for a player without the LoW DLC? He should still be able to join the mission, I guess - so what exactly happens if he is on a slot where the DLC stuff is used?

If there is no or only a minor impact, we can probably keep it as it is - otherwise we can probably change the display and class name to something like this to raise awareness:

_Messenger Bag (Black, Medical) [LoW DLC]
ga_dlc_low_messenger_black_medic_

**Comment by Fusselwurm** [comment]
@Synch2k afaik, gear will just not be applied. We had a similar problem in a Dark Business event once, where half the players didnt own Apex… I think they didnt notice - except that they didnt have any guns :roll_eyes: 

So, adding a hint to LoW in the description/title text is probably good enough.

**Comment by Synch2k** [comment]
if i can find someone without LoW DLC, i'll run a quick test to be sure and then make changes (or not)

**Comment by McDiod** [comment]
What's the status here?

**Comment by nomisum** [comment]
soonTM

**Comment by Synch2k** [comment]
image

**Comment by Synch2k** [comment]
didn't had the chance to test LoW based content with a non LoW user - to be sure last commit should make it clear that the messenger bags are based on DLC content

**Comment by McDiod** [comment]
Base class is:

```
class B_Messenger_Base_F: Bag_Base {
		author = "$STR_A3_Bohemia_Interactive";
		mapSize = 0.470000;
		_generalMacro = "B_Messenger_Base_F";
		scope = 0;
		hiddenSelections = {"Camo"};
		DLC = "Orange";
		model = "\A3\Supplies_F_Orange\Bags\B_Messenger_F.p3d";
		maximumLoad = 140;
		mass = 20;
	};
```

So maybe just do `DLC = "";` and that's all we need?

**Comment by nomisum** [comment]
> Base class is:
> 
> ```
> class B_Messenger_Base_F: Bag_Base {
> 		author = "$STR_A3_Bohemia_Interactive";
> 		mapSize = 0.470000;
> 		_generalMacro = "B_Messenger_Base_F";
> 		scope = 0;
> 		hiddenSelections = {"Camo"};
> 		DLC = "Orange";
> 		model = "\A3\Supplies_F_Orange\Bags\B_Messenger_F.p3d";
> 		maximumLoad = 140;
> 		mass = 20;
> 	};
> ```
> So maybe just do `DLC = "";` and that's all we need?

Dont understaaand... why empty string when there is a dependency on Orange DLC?

**Pull request merged**
